### ISSUE TITLE
Error during Migration

### ISSUE THREAD

**Issue by solamichealolawale** [usamamuneerchaudhary/country-city-state#1]
This is the error I got after running migration

![image](https://user-images.githubusercontent.com/12444227/103403026-11ea4f00-4b4f-11eb-97c7-337cce3bc084.png)

**Comment by rantech-za** [comment]
Change line 61 of 2014_02_04_000000_create_country_state_city_table.php to 

`$table->unsignedBigInteger('country_id');`

**Comment by usamamuneerchaudhary** [comment]
updated on the latest release, thanks @rantech-za
